#========================================
# General settings
#========================================
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: contract-loader
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: dbconnection-pool
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
    show-sql: false
  security:
    oauth2:
      client:
        provider:
          party:
            token-uri: ${integration.party.token-uri}
          contract:
            token-uri: ${integration.contract.token-uri}
          estateinfo:
            token-uri: ${integration.estateinfo.token-uri}
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party
            client-id: ${integration.party.client-id}
            client-secret: ${integration.party.client-secret}
          contract:
            authorization-grant-type: client_credentials
            provider: contract
            client-id: ${integration.contract.client-id}
            client-secret: ${integration.contract.client-secret}
          estateinfo:
            authorization-grant-type: client_credentials
            provider: estateinfo
            client-id: ${integration.estateinfo.client-id}
            client-secret: ${integration.estateinfo.client-secret}

integration:
  party:
    connectTimeout: 10
    readTimeout: 20
  contract:
    connectTimeout: 10
    readTimeout: 20
  estateinfo:
    connectTimeout: 10
    readTimeout: 20